#
# Copyright 2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-tls-delete"
  labels:
    name: ibm-elastic-stack-operator
    app.kubernetes.io/instance: common-logging
    app.kubernetes.io/managed-by: elasticstacks.elasticstack.ibm.com
    app.kubernetes.io/name: elasticstacks.elasticstack.ibm.com
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app "tls-delete" "cleanup") | indent 8 }}
spec:
  backoffLimit: 90
  template:
    metadata:
      labels:
        name: ibm-elastic-stack-operator
        app.kubernetes.io/instance: common-logging
        app.kubernetes.io/managed-by: elasticstacks.elasticstack.ibm.com
        app.kubernetes.io/name: elasticstacks.elasticstack.ibm.com
{{ include "metadata.calculateLabels" (list . $app "tls-delete" "cleanup") | indent 8 }}
      annotations:
{{ include "metadata.calculateAnnotations" (list . ) | indent 8 }}
    spec:
      restartPolicy: OnFailure
{{ include "image.pullSecret" . | indent 6 }}
{{- if .Values.elasticsearch.data.tolerations }}
      tolerations:
{{ toYaml .Values.elasticsearch.data.tolerations | indent 6 }}
{{- end }}
{{- if .Values.elasticsearch.data.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.elasticsearch.data.nodeSelector | indent 8 }}
{{- end }}
      serviceAccountName: "{{ template "job.fullname" . }}"
      containers:
      - name: cleanup
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsNonRoot: true
        image: {{ .Values.kibana.initImage.repository }}:{{ .Values.kibana.initImage.tag }}
        command: ["/opt/entry/cleanup.sh"]
        volumeMounts:
          - mountPath: "/opt/entry"
            name: entrypoint
{{- if .Values.elasticsearch.security.authc.enabled }}
          - name: certs
            mountPath: "/usr/share/elasticsearch/config/tls"
            readOnly: true
{{- end }}
      volumes:
      - name: entrypoint
        configMap:
          name: {{ template "elasticsearch.fullname" . }}-tls-cleanup
          defaultMode: 0777
{{- if .Values.elasticsearch.security.authc.enabled }}
      - name: certs
        secret:
          secretName: {{ template "fullname" . }}-certs
{{- end }}
